# Generated by Django 4.0.3 on 2023-04-25 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='import_href',
        ),
    ]
